#!/usr/bin/env bash
# Start a local Solana test validator with the Pop programs and the real Raydium CP-Swap program preloaded,
# using the pinned Anchor/Solana Docker image so no host toolchain is required.
#   scripts/localnet.sh start   # starts (or restarts) the validator in the background
#   scripts/localnet.sh stop
#   scripts/localnet.sh logs
# Fixtures (tests/fixtures):
#   raydium_cp_swap.so            built from source by scripts/raydium-fixture.sh (localnet admin feature)
#   create_pool_fee_account.json  Raydium's hardcoded pool-creation fee receiver (a wrapped-SOL token account),
#                                 generated by tests/integration/scripts/raydium-fee-account.mjs
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
IMAGE="${POP_ANCHOR_IMAGE:-solanafoundation/anchor:v1.0.2}"
NAME="pop-localnet"
MARKET_ID="$(grep -oE 'pop_market = "[^"]+"' "$ROOT/Anchor.toml" | head -1 | cut -d'"' -f2)"
LAUNCH_ID="$(grep -oE 'pop_launch = "[^"]+"' "$ROOT/Anchor.toml" | head -1 | cut -d'"' -f2)"
RAYDIUM_ID="CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C"
FEE_ACCOUNT="DNXgeM9EiiaAbaWvwjHj9fQQLAX5ZsfHyvmYUNRAdNC8"
case "${1:-start}" in
  start)
    docker rm -f "$NAME" >/dev/null 2>&1 || true
    for f in target/deploy/pop_market.so target/deploy/pop_launch.so tests/fixtures/raydium_cp_swap.so tests/fixtures/create_pool_fee_account.json; do
      [ -f "$ROOT/$f" ] || { echo "missing $f (build first: scripts/build-program.sh, scripts/raydium-fixture.sh, node tests/integration/scripts/raydium-fee-account.mjs)"; exit 1; }
    done
    # Agave 3.x accounts-db requires io_uring, which Docker's default seccomp profile blocks.
    mkdir -p "$ROOT/.anchor/test-ledger"
    docker run -d --name "$NAME" --network host --security-opt seccomp=unconfined \
      -v "$ROOT:/work" -v "$ROOT/.anchor/test-ledger:/ledger" -w /work "$IMAGE" \
      solana-test-validator --reset --bind-address 127.0.0.1 --rpc-port 8899 --limit-ledger-size 10000000 \
      --ledger /ledger \
      --bpf-program "$MARKET_ID" /work/target/deploy/pop_market.so \
      --bpf-program "$LAUNCH_ID" /work/target/deploy/pop_launch.so \
      --bpf-program "$RAYDIUM_ID" /work/tests/fixtures/raydium_cp_swap.so \
      --account "$FEE_ACCOUNT" /work/tests/fixtures/create_pool_fee_account.json >/dev/null
    echo "waiting for validator on http://127.0.0.1:8899 ..."
    for i in $(seq 1 90); do
      if curl -sS -X POST -H 'content-type: application/json' -d '{"jsonrpc":"2.0","id":1,"method":"getHealth"}' http://127.0.0.1:8899 2>/dev/null | grep -q ok; then
        echo "validator ready (pop_market $MARKET_ID, pop_launch $LAUNCH_ID, raydium $RAYDIUM_ID)"; exit 0; fi
      sleep 1
    done
    echo "validator did not become healthy"; docker logs "$NAME" | tail -20; exit 1 ;;
  stop) docker rm -f "$NAME" >/dev/null 2>&1 && echo stopped ;;
  logs) docker logs -f "$NAME" ;;
  *) echo "usage: $0 start|stop|logs"; exit 1 ;;
esac
