import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { ALL_SCENARIOS } from "./scenarios.js";
import { serializeReport } from "./serialize.js";
import type { RunReport } from "./engine.js";

const outDir = resolve(process.argv[2] ?? "../../docs/sim-results");
mkdirSync(outDir, { recursive: true });
const only = process.argv[3];
const summary: string[] = ["# Simulator scenario results", "", `Generated by \`pnpm sim\` on ${new Date().toISOString()}. Deterministic; re-run to reproduce. These are simulator outputs, not validator evidence.`, ""];
for (const s of ALL_SCENARIOS) {
  if (only && s.id !== only) continue;
  const t0 = performance.now();
  const out = s.run();
  const reports: RunReport[] = Array.isArray(out) ? out : [out];
  const ms = (performance.now() - t0).toFixed(0);
  summary.push(`## ${s.title}`, "", `Scenario id: \`${s.id}\` (${ms} ms)`, "");
  for (const r of reports) {
    const file = resolve(outDir, `${r.name}.json`);
    writeFileSync(file, serializeReport(r));
    summary.push(`### Run \`${r.name}\` (${r.configLabel})`, "", r.description, "", `Trades: ${r.tradeCount.succeeded} ok / ${r.tradeCount.failed} failed. Reconciliation: ${r.reconciliation.ok ? "OK" : "FAILED"}. Status: ${r.matched.status}. Paired quote: ${r.matched.pairedQuoteLifetime} lamports. Hardened bands: ${r.matched.hardenedBands}.`, "");
    for (const f of r.findings) summary.push(`- ${f}`);
    summary.push("");
    console.log(`[${s.id}] ${r.name}: ${r.tradeCount.succeeded} ok / ${r.tradeCount.failed} failed, reconcile=${r.reconciliation.ok}, status=${r.matched.status}`);
    if (!r.reconciliation.ok) process.exitCode = 1;
  }
}
writeFileSync(resolve(outDir, "SUMMARY.md"), summary.join("\n"));
console.log(`wrote ${outDir}/SUMMARY.md`);
